"""rename department

Revision ID: 622470beb9af
Revises: 91a20ad4d328
Create Date: 2024-02-21 14:58:46.878999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622470beb9af'
down_revision = '91a20ad4d328'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('departments',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('name', sa.String(), nullable=False),
#     sa.Column('address', sa.String(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.drop_table('department')
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('department',
#     sa.Column('id', sa.INTEGER(), nullable=False),
#     sa.Column('name', sa.VARCHAR(), nullable=False),
#     sa.Column('address', sa.VARCHAR(), nullable=True),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.drop_table('departments')
#     # ### end Alembic commands ###

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
